Data Base connection
Regis18/ToolSearch pull request #11
Opened 2019-02-21 23:51 UTC by Cxristian

implements query and connections

2019-02-22 01:05 UTC, jpsandovaln commented on src/main/java/com/jala/data/ConnectionDB.java
> + * @Version 21/02/2019/C
the version should be number and not date, please review the previous files merged to develop

2019-02-22 01:05 UTC, jpsandovaln commented on src/main/java/com/jala/data/ConnectionDB.java
> +
remove extra line

2019-02-22 01:06 UTC, jpsandovaln commented on src/main/java/com/jala/data/ConnectionDB.java
> +     * @return The connection
add documentation for this method

2019-02-22 01:06 UTC, jpsandovaln commented on src/main/java/com/jala/data/QueryGeneral.java
> + * @Version 21/02/2019/C
use version number

2019-02-22 01:06 UTC, jpsandovaln commented on src/main/java/com/jala/data/QueryGeneral.java
> +
remove extra line

2019-02-22 01:07 UTC, jpsandovaln commented on src/main/java/com/jala/data/QueryGeneral.java
> +     * Method
we need to improve this documentation

2019-02-22 01:07 UTC, jpsandovaln commented on src/main/java/com/jala/data/QueryGeneral.java
> +     *
Add documentation

2019-02-22 01:07 UTC, jpsandovaln commented on src/main/java/com/jala/data/QueryGeneral.java
> +     *
Add documentation

2019-02-22 01:07 UTC, jpsandovaln commented on src/main/java/com/jala/data/QueryGeneral.java
> +     *
Add documentation

2019-02-22 01:10 UTC, jpsandovaln commented on src/main/java/com/jala/data/QueryGeneral.java
> +}
add extra line at end of file

2019-02-22 01:56 UTC, AKatrin requested changes

2019-02-22 01:56 UTC, AKatrin commented on src/main/java/com/jala/data/ConnectionDB.java
> +    private static ConnectionDB connectDB;
Add documentation

2019-02-22 01:56 UTC, AKatrin commented on src/main/java/com/jala/data/ConnectionDB.java
> +    public Connection getConnection(){
Add a space before {

2019-02-23 04:12 UTC, AKatrin requested changes

2019-02-23 04:12 UTC, AKatrin commented on src/main/java/com/jala/data/ConnectionDB.java
> +    private static Connection connection;
add documentation

2019-02-23 04:12 UTC, AKatrin commented on src/main/java/com/jala/data/ConnectionDB.java
> +    private static ConnectionDB connectDB;
add documentation

2019-02-23 04:12 UTC, AKatrin commented on src/main/java/com/jala/data/ConnectionDB.java
> +     * @return Connectionqwe of Data Base
Connectionqwe???

2019-02-23 04:12 UTC, AKatrin commented on src/main/java/com/jala/data/QueryGeneral.java
> +    private Connection connection;
add documentation please

2019-02-23 04:12 UTC, AKatrin commented on src/main/java/com/jala/data/QueryGeneral.java
> +}
you do a pull of develop branch and do merge

2019-02-25 14:57 UTC, merged