Add Unit Test of Search Common with SearchCommon 100% and lines 100%
Regis18/ToolSearch pull request #111
Opened 2019-03-29 14:06 UTC by Regis18

2019-03-29 15:11 UTC, AKatrin requested changes
Please apply code format and write a documentation more specific

2019-03-29 15:11 UTC, AKatrin commented on src/test/java/com/jala/model/search/SearchCommonTest.java
> +	CriteriaSearch criteriaSearch;
please add empty line before and after the atribute

2019-03-29 15:11 UTC, AKatrin commented on src/test/java/com/jala/model/search/SearchCommonTest.java
> +		assertEquals(expected,actual);
add a space after ","

2019-03-29 15:11 UTC, AKatrin commented on src/test/java/com/jala/model/search/SearchCommonTest.java
> +    /**
Apply format code

2019-03-29 15:11 UTC, AKatrin commented on src/test/java/com/jala/model/search/testfiles/test2.txt
> +Command line instructions
delete this file please

2019-03-29 15:11 UTC, AKatrin commented on src/test/java/com/jala/model/search/testfiles/test3.txt
> +Cloud computing
Why is this file ???

2019-03-29 15:25 UTC, Regis18 commented on src/test/java/com/jala/model/search/testfiles/test3.txt
> +Cloud computing
This file is for testing, is a folder of testfile

2019-03-29 15:37 UTC, AKatrin commented on src/test/java/com/jala/model/search/testfiles/test3.txt
> +Cloud computing
You can create the folder "resources" at "src/test/" and add this file on "resources"

2019-03-30 03:33 UTC, raultolive commented on src/test/java/com/jala/model/search/SearchCommonTest.java
> +	 */
this 35,36 and 37 are without comment clear or comment please

2019-03-30 03:35 UTC, raultolive commented on src/test/java/com/jala/model/search/SearchCommonTest.java
> +     */
justify this line

2019-03-30 03:35 UTC, raultolive commented on src/test/java/com/jala/model/search/SearchCommonTest.java
> +     */
Justify this line

2019-03-30 03:35 UTC, raultolive commented on src/test/java/com/jala/model/search/SearchCommonTest.java
> +     */
justify this line

2019-03-30 03:43 UTC, Regis18 commented on src/test/java/com/jala/model/search/testfiles/test2.txt
> +Command line instructions
I won't erase that file because is for testing to search files

2019-03-30 03:43 UTC, Regis18 commented on src/test/java/com/jala/model/search/SearchCommonTest.java
> +     */
What means that?

2019-03-30 03:46 UTC, raulchoque-eng approved these changes

2019-03-30 03:47 UTC, merged