add criteria hidden and hidden search file
Regis18/ToolSearch pull request #25
Opened 2019-02-26 13:12 UTC by melvicaballero

Add criteria hidden and hidden search file.

2019-02-26 15:23 UTC, AKatrin requested changes

2019-02-26 15:23 UTC, AKatrin commented on src/main/java/com/jala/search/models/SearchFile.java
> +                        boolean hiddenYN = true;
what is hiddenYN?

2019-02-26 15:23 UTC, AKatrin commented on src/main/java/com/jala/search/models/SearchFile.java
> +                        if (!hiddenCriteria && file.isHidden()) {
this if can be of following form:
`
if ((hiddenCriteria && !file.isHidden()) || (!hiddenCriteria && file.isHidden()) ) {
      hiddenYN=false;
  }
`

2019-02-26 15:23 UTC, AKatrin commented on src/main/java/com/jala/search/models/SearchFile.java
> +                        if (!nameCriteria.isEmpty()) {
you can join the if with && for example 
`
if (!nameCriteria.isEmpty() && !nameFile.contains(nameCriteria)) {
    hiddenYN = false;
}
`

2019-02-26 15:41 UTC, AKatrin requested changes

2019-02-26 15:41 UTC, AKatrin commented on src/main/java/com/jala/search/models/SearchFile.java
> +
Delete empty line

2019-02-26 15:41 UTC, AKatrin commented on src/main/java/com/jala/search/models/SearchFile.java
> +                        if (!extensionCriteria.isEmpty()) {
> you can join the if with && for example

2019-02-26 16:42 UTC, AKatrin approved these changes

2019-02-26 17:51 UTC, Cxristian approved these changes

2019-02-28 04:55 UTC, Regis18 commented on src/main/java/com/jala/search/models/AssetCommon.java
> +
borrar espacios extras

2019-02-28 04:55 UTC, Regis18 commented on src/main/java/com/jala/search/models/SearchFile.java
> +                        // var aux.
Delete innecesary comment

2019-02-28 04:55 UTC, Regis18 commented on src/main/java/com/jala/search/models/SearchFile.java
> +                        if (addFileToResults && criteria.getHidden() == TernaryBooleanEnum.OnlyFalse && asset.isHidden()){
Spacio between the condition and the key

2019-02-28 04:55 UTC, Regis18 commented on src/main/java/com/jala/search/models/SearchFile.java
> +                        if(addFileToResults && (criteria.getReadonly() == TernaryBooleanEnum.OnlyTrue) && !(asset).isReadOnly()){
Put  a spacio between condition and key

2019-02-28 04:55 UTC, Regis18 commented on src/main/java/com/jala/search/models/SearchFile.java
> +                        if(addFileToResults && (criteria.getReadonly() == TernaryBooleanEnum.OnlyFalse) && (asset).isReadOnly()){
Spacio between condition and key

2019-02-28 04:55 UTC, Regis18 commented on src/main/java/com/jala/search/models/TernaryBooleanEnum.java
> +
It can be in the package of Utils?

2019-02-28 13:42 UTC, Regis18 approved these changes

2019-02-28 13:43 UTC, merged