Refactor criterias class and add a new class CriteriaSearchVideo
Regis18/ToolSearch pull request #46
Opened 2019-03-08 13:07 UTC by melvicaballero

Refactor criteria family and add a new CriteriaSearchVideo class.

2019-03-08 21:15 UTC, AKatrin requested changes

2019-03-08 21:15 UTC, AKatrin commented on src/main/java/com/jala/common/models/Criteria.java
> +    public Criteria(){};
Add space between ")" and "{"

2019-03-08 21:15 UTC, AKatrin commented on src/main/java/com/jala/search/models/CriteriaSearch.java
> +    }
Add a empty line after "{"

2019-03-08 21:15 UTC, AKatrin commented on src/main/java/com/jala/search/models/CriteriaSearchVideo.java
> +    private String path;
Add documentation to the attributes

2019-03-08 21:15 UTC, AKatrin commented on src/main/java/com/jala/search/models/CriteriaSearchVideo.java
> +
Delete empty line

2019-03-08 21:15 UTC, AKatrin commented on src/main/java/com/jala/search/models/CriteriaSearchVideo.java
> +    private void LoadVideoCriteria(){
The name methods should start with lowercase

2019-03-08 21:15 UTC, AKatrin commented on src/main/java/com/jala/search/models/CriteriaSearchVideo.java
> +    public CriteriaSearchVideo(String path) {
The name methods should start with lowercase

2019-03-08 21:15 UTC, AKatrin commented on src/main/java/com/jala/search/models/CriteriaSearchVideo.java
> +    }
Add empty line after "}"

2019-03-08 21:15 UTC, AKatrin commented on src/main/java/com/jala/search/models/CriteriaSearchVideo.java
> +     * @param dimension set dimension attribute os video search.
change "os" to "of"

2019-03-08 21:15 UTC, AKatrin commented on src/main/java/com/jala/search/models/CriteriaSearchVideo.java
> +    private String aspecRatio;
Rename "aspecRatio" to "aspectRatio"

2019-03-09 20:39 UTC, melvicaballero commented on src/main/java/com/jala/search/models/CriteriaSearchVideo.java
> +    public CriteriaSearchVideo(String path) {
This method is a constructor.

2019-03-10 02:11 UTC, Regis18 commented on src/main/java/com/jala/search/models/CriteriaSearchMultimedia.java
> +    private void LoadVideoCriteria() {
The first letter of the method has to be lower case... loadVideoCriteria

2019-03-11 15:37 UTC, Regis18 approved these changes

2019-03-11 15:38 UTC, merged