Refactor Search with video and audio
Regis18/ToolSearch pull request #66
Opened 2019-03-18 17:28 UTC by Regis18

Search video and audio

2019-03-18 19:49 UTC, raultolive commented on src/main/java/com/jala/model/search/SearchAudio.java
> +
Clear this line.

2019-03-18 19:52 UTC, raultolive commented on src/main/java/com/jala/model/search/SearchBasic.java
> +	/**
Justify this comment.

2019-03-18 19:55 UTC, raultolive commented on src/main/java/com/jala/model/search/SearchCommon.java
> +	/**
Justify this comment.

2019-03-18 19:56 UTC, raultolive commented on src/main/java/com/jala/model/search/SearchCommon.java
> +    /** It creates to follow up the instruction of the class*/
Add a line above this line..

2019-03-18 19:59 UTC, raultolive commented on src/main/java/com/jala/model/search/SearchFile.java
> +     * @param criteria
Complete this comment.

2019-03-18 20:05 UTC, raultolive commented on src/main/java/com/jala/model/search/SearchVideo.java
> +		log.info("The search for Video is beginning");
Justify only four spaces.

2019-03-18 20:09 UTC, raultolive commented on src/main/java/com/jala/model/search/asset/Asset.java
> +    /**
Add a line above this line.

2019-03-18 23:34 UTC, AKatrin requested changes

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchAudio.java
> + * SearchAudio
Complete documentation please.

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchAudio.java
> +                if (resultSearchAudio && !(ffprobeResult.getStreams().get(0).codec_long_name).contains(criteriaSearchAudio.getAudioCodec())) {
`get(0)` the same parameter is used in other line please create a constant for this parameter

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchAudio.java
> +                    if (!criteriaSearchAudio.getAudioCodec().equals("")) {
create constant to empty value "" or use the methos `empty()`

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchAudio.java
> +                    double durationCriteria = Double.parseDouble(criteriaSearchAudio.getDuration()) * 60;
use constant for value 60 please

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchBasic.java
> +    private static Logger log = Logs.getInstance().getLog();
add a empty line between attributes

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchBasic.java
> +	/**
format you documentation please

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchBasic.java
> +     * @param filePath the path of the file.
add a empty line between documentation and param

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchBasic.java
> +    public static String fileCreationDate(String filePath) {
the name of method start with verb please rename this method

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchBasic.java
> +        BasicFileAttributes attrs;
use a name specific please in attrs

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchBasic.java
> +            formatted = simpleDateFormat.format( new java.util.Date( time.toMillis() ) );
format in the "( )"

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchBasic.java
> +    public static String fileLastModifiedDate(String filePath) {
rename the method please this should start with a verb

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchCommon.java
> + * SearchCommon.
add documentation for classes

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchCommon.java
> +    private CriteriaSearch criteria;
add documentation for attributes

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchCommon.java
> +    private CriteriaSearch criteria;
add a empty line between attributes

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchCommon.java
> +                if ((Date.valueOf(fileCreationDate(preview.get(i).getPath())).before(Date.valueOf(criteria.getCreationDateFrom())))
cut line please it is very long

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchFile.java
> + * @author Regis Humana.
is need to change the author???

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchFile.java
> +     * @param criteria
add documentation for params

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchVideo.java
> + * SearchVideo.
Add documentation for description of class please

2019-03-18 23:34 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchVideo.java
> +	/** Criteria multimedia. */
what should be used to documentation of attributes 
`/**
* Asset list.
*/`
or
/** Criteria multimedia. */

2019-03-19 03:46 UTC, raultolive commented on src/main/java/com/jala/model/search/asset/AssetAudio.java
>      /**
Add a line above.

2019-03-19 03:49 UTC, raultolive commented on src/main/java/com/jala/model/search/asset/AssetFactory.java
Clear this line.

2019-03-19 03:54 UTC, raultolive commented on src/main/java/com/jala/model/search/asset/AssetVideo.java
Clear this line.

2019-03-19 03:56 UTC, raultolive commented on src/main/java/com/jala/model/search/asset/AssetVideo.java
>       *
Clear this line.

2019-03-19 04:04 UTC, raultolive commented on src/main/java/com/jala/utils/AssetFactory.java
> +
Clear this line.

2019-03-19 04:05 UTC, raultolive commented on src/test/java/com/jala/model/search/SearchAudioTest.java
> +
Clear this line.

2019-03-19 04:07 UTC, raultolive commented on src/test/java/com/jala/model/search/SearchCommonTest.java
> +import static org.junit.Assert.*;
Put the complete import.

2019-03-19 04:09 UTC, raultolive commented on src/test/java/com/jala/model/search/SearchVideoTest.java
> +		criteria.setExtension("mp4");
Justify only four spaces.

2019-03-19 15:01 UTC, AKatrin commented on src/main/java/com/jala/model/search/SearchCommon.java
> +    /** It creates to follow up the instruction of the class*/
please add dot in documentation

2019-03-19 15:32 UTC, raultolive commented on src/main/java/com/jala/model/criteria/CriteriaConverterVideo.java
Clear this line.

2019-03-19 15:34 UTC, raultolive commented on src/main/java/com/jala/model/criteria/CriteriaConverterVideo.java
Then clear the line 162

2019-03-19 15:35 UTC, raultolive commented on src/main/java/com/jala/model/criteria/CriteriaSearch.java
> +
Clear this line.

2019-03-19 15:39 UTC, raultolive commented on src/main/java/com/jala/model/search/SearchBasic.java
> +	/**
Justify this comment.

2019-03-19 15:41 UTC, raultolive commented on src/main/java/com/jala/model/search/SearchCommon.java
> +	/**
Justify this comment.

2019-03-19 15:42 UTC, raultolive commented on src/main/java/com/jala/model/search/SearchCommon.java
> +	/**
Justify this comment.

2019-03-19 15:49 UTC, raultolive commented on src/main/java/com/jala/model/search/asset/AssetAudio.java
>  /**
Add an space above.

2019-03-19 15:51 UTC, raultolive commented on src/main/java/com/jala/model/search/asset/AssetVideo.java
Clear this line.

2019-03-19 16:19 UTC, merged